spring:
  datasource:
    url : jdbc:mysql://localhost:3306/rewardsandrecognition
    username : root
    password : Khalyan123#k
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL80InnoDBDialect
        jdbc:
          time_zone: UTC